fix: Java file diagnostics is not refreshed when properties file is saved
redhat-developer/intellij-quarkus pull request #1084
Opened 2023-08-08 18:07 UTC by angelozerr

fix: Java file diagnostics is not refreshed when properties file is saved

Fixes #860

2023-09-08 13:53 UTC, fbricon commented on src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/AbstractConfigSource.java
> +import io.quarkus.deployment.util.IoUtil;
unused

2023-09-08 14:02 UTC, fbricon commented on src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/documentation/LSPDocumentationProvider.java
>          if (originalElement == null || !Objects.equals(element.getContainingFile(), originalElement.getContainingFile())) {
might as well remove the if block

2023-09-08 15:01 UTC, angelozerr commented on src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/AbstractConfigSource.java
> +import io.quarkus.deployment.util.IoUtil;
fixed

2023-09-08 15:01 UTC, angelozerr commented on src/main/java/com/redhat/devtools/intellij/lsp4ij/operations/documentation/LSPDocumentationProvider.java
>          if (originalElement == null || !Objects.equals(element.getContainingFile(), originalElement.getContainingFile())) {
my bad -( fixed

2023-09-08 16:19 UTC, fbricon commented
Works great. Let's merge after CI passes

2023-09-09 11:24 UTC, fbricon requested changes

2023-09-09 11:24 UTC, fbricon commented on src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProject.java
> +     * <p>
missing closing tag

2023-09-09 11:24 UTC, fbricon commented on src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProject.java
> +     * <p>
missing closing tag

2023-09-09 11:24 UTC, fbricon commented on src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProject.java
> +     * <p>
missing closing tag

2023-09-10 06:35 UTC, angelozerr commented on src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProject.java
> +     * <p>
fixed

2023-09-10 08:31 UTC, fbricon commented on src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProject.java
> +    private IConfigSource findCounfigSource(VirtualFile file) {
findConfigSource

2023-09-10 09:19 UTC, angelozerr commented on src/main/java/com/redhat/devtools/intellij/lsp4mp4ij/psi/core/project/PsiMicroProfileProject.java
> +    private IConfigSource findCounfigSource(VirtualFile file) {
fixed

2023-09-10 09:19 UTC, angelozerr commented
>Works great. Let's merge after CI passes

CI are passed

2023-09-10 11:30 UTC, merged

2023-09-10 11:30 UTC, fbricon commented
Thanks @angelozerr