Add method to take fullscreen screenshots during running the UI tests
redhat-developer/intellij-quarkus pull request #346
Opened 2021-01-13 11:33 UTC by zcervink

- Remote-Robot itself does not offer method for taking screenshot (reported: https://github.com/JetBrains/intellij-ui-test-robot/issues/18, will be probably implemented in the future)
- for now I extend GlobalUtils to contain method for taking screenshots

Fixes #345

Signed-off-by: Zbynek Cervinka <zcervink@redhat.com>

Please review @jrichter1 @jeffmaury

2021-01-13 18:23 UTC, jeffmaury requested changes

2021-01-13 18:23 UTC, jeffmaury commented on src/it/java/org/jboss/tools/intellij/quarkus/utils/GlobalUtils.java
> +import java.awt.*;
Star imports are not accepted

2021-01-14 14:31 UTC, jeffmaury approved these changes

2021-01-14 16:39 UTC, zcervink commented
@jeffmaury The checks finish and are green. I think, we can merge. (I think the review from @jrichter1 will not be needed after all).

2021-01-14 16:47 UTC, merged