chore(skip-release): Prepare for 1.19.0
redhat-developer/intellij-quarkus pull request #878
Opened 2023-05-23 18:26 UTC by adietish

2023-05-23 19:14 UTC, angelozerr commented
@adietish there are so many changes in this release with the start stop of language server and lsp console.

Thats why it should be [1.19.0](https://github.com/redhat-developer/intellij-quarkus/milestone/30)

2023-05-24 07:01 UTC, fbricon requested changes

2023-05-24 07:01 UTC, fbricon commented on src/main/resources/META-INF/plugin.xml
> +      <li>LSP console to track LSP request/responses notification for all started language server</li>
language servers

2023-05-24 07:01 UTC, fbricon commented on src/main/resources/META-INF/plugin.xml
> +      <li>performance improvement which should avoid freezing IJ by improving start/stop of language server</li>
servers

2023-05-24 08:49 UTC, adietish commented on src/main/resources/META-INF/plugin.xml
> +      <li>performance improvement which should avoid freezing IJ by improving start/stop of language server</li>
corrected

2023-05-24 08:49 UTC, adietish commented on src/main/resources/META-INF/plugin.xml
> +      <li>LSP console to track LSP request/responses notification for all started language server</li>
corrected

2023-05-24 08:51 UTC, adietish commented
@fbricon, @angelozerr please re-review

2023-05-24 08:55 UTC, merged

2023-05-24 08:56 UTC, fbricon commented
@adietish thanks, please proceed with the release

2023-05-24 09:08 UTC, adietish commented
plugin 1.19.0.388 is available on jetbrains marketplace at https://plugins.jetbrains.com/plugin/13234-quarkus-tools/versions/stable/338515